feat: company api load update
team5-ViewMyStartup/2-view-my-startup-5-FE pull request #19
Opened 2024-10-05 09:32 UTC by gahyeon-yang

### 🔎 작업 내용

#### 기업리스트

- 기업 리스트 불러오기
- 기업 리스트 클릭 시 상세 페이지 넘어가기

#### 비교현황

- 비교현황 리스트 불러오기
- 드롭다운 박스 옵션 변경
- 링크 설정 시 글자 색 변경이 됨으로 color D8D8D8로 설정

#### 투자현황

- 투자현황 리스트 불러오기
- 리스트 헤더 수정

2024-10-05 17:31 UTC, MCprotein requested changes

2024-10-05 17:31 UTC, MCprotein commented on src/api/api.js
>  const BASE_URL = "http://localhost:4000";
@gahyeon-yang 이거 왜 환경변수 안쓰고 하드코딩해서 쓰고있나요?

2024-10-05 17:31 UTC, MCprotein commented on src/api/api.js
>  };
@gahyeon-yang 이렇게 하지말고 공통함수 하나만들고 endpoint만 parameter로 넘기게해서 사용하세요

2024-10-05 17:39 UTC, gahyeon-yang commented on src/api/api.js
>  };
{BASE_URL}${endpoint} 이 함수 만들고 ()＋fetchData('/companies');랑 파라미터 (companyId) 주고 fetchData('/companies/${companyId}'); 분리하는 거 말씀이실까요?

2024-10-05 17:53 UTC, MCprotein commented on src/api/api.js
>  };
잘 이해는 안되지만 아래처럼 구성하시면 돼요



```js
const HTTP_METHODS = Object.freeze({
  GET: 'GET',
  POST: 'POST,
  ...
})

export function fetchData({url, status, data, options}) {
  
  
}

export function getFetchData(url, options) {
  return await fetchData({url, status: HTTP_METHODS.GET, options})
}
```

2024-10-05 17:55 UTC, gahyeon-yang commented on src/api/api.js
>  };
넵 너무 비몽사몽으로 회신했네요... 참고해서 응용하겠습니다!

2024-10-05 17:58 UTC, MCprotein commented on src/api/api.js
>  };
@gahyeon-yang 잘때는 이메일 알림 꺼주세요.. 저때매 깨신거같은데 죄송하네요

2024-10-05 17:59 UTC, gahyeon-yang commented on src/api/api.js
>  };
아니요.. 배고파서 깼습니다...ㅎ

2024-10-05 18:01 UTC, MCprotein commented on src/api/api.js
>  };
@gahyeon-yang 아... ㅋㅋㅋ 
낼 백엔드 pr이랑 슬랙도 함 확인해주세요
얼렁뭐드시고 주무시죠

2024-10-05 18:02 UTC, gahyeon-yang commented on src/api/api.js
>  };
넵!🫡

2024-10-06 06:44 UTC, merged

2024-10-06 16:42 UTC, gahyeon-yang commented on src/api/api.js
>  const BASE_URL = "http://localhost:4000";
.env로 변경했습니다.